// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2KEmaxzaAUi7hIPlStYCmreLUHb0r9Kg',
    appId: '1:75459877224:web:3771fbd1cbeff900559edd',
    messagingSenderId: '75459877224',
    projectId: 'docvartaa',
    authDomain: 'docvartaa.firebaseapp.com',
    storageBucket: 'docvartaa.firebasestorage.app',
    measurementId: 'G-TYKBJVQ00P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtx19Zwz2DwHE0p9hwgjsHKeqLqEzKU2U',
    appId: '1:75459877224:android:01d819310e61eb87559edd',
    messagingSenderId: '75459877224',
    projectId: 'docvartaa',
    storageBucket: 'docvartaa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIRm8gPvvERb3kYjnLstaqIsVC8VcXicY',
    appId: '1:75459877224:ios:73013611e9ea8bb4559edd',
    messagingSenderId: '75459877224',
    projectId: 'docvartaa',
    storageBucket: 'docvartaa.firebasestorage.app',
    iosBundleId: 'com.example.docvartaa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIRm8gPvvERb3kYjnLstaqIsVC8VcXicY',
    appId: '1:75459877224:ios:73013611e9ea8bb4559edd',
    messagingSenderId: '75459877224',
    projectId: 'docvartaa',
    storageBucket: 'docvartaa.firebasestorage.app',
    iosBundleId: 'com.example.docvartaa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2KEmaxzaAUi7hIPlStYCmreLUHb0r9Kg',
    appId: '1:75459877224:web:f5c589be4c123822559edd',
    messagingSenderId: '75459877224',
    projectId: 'docvartaa',
    authDomain: 'docvartaa.firebaseapp.com',
    storageBucket: 'docvartaa.firebasestorage.app',
    measurementId: 'G-GMF37NL1BY',
  );

}